pub const MASCOT_ANIMATION_REFRESH_MS: u64 = 33;
pub const MASCOT_STATE_TRANSITION_SECONDS: f64 = 0.24;
pub const MASCOT_IDLE_LONG_SECONDS: u64 = 120;
pub const MASCOT_WAKE_ANGRY_SECONDS: f64 = 0.82;
pub const MASCOT_VERTICAL_NUDGE_Y: f64 = -2.0;
