pub const PANEL_HIGHLIGHT_MAX_ALPHA: f64 = 0.12;
pub const PANEL_VISIBILITY_EPSILON: f64 = 0.02;
pub const PANEL_COMPACT_CORNER_MASK_MAX_PROGRESS: f64 = 0.01;
pub const PANEL_EDGE_ACTIONS_REVEAL_START_PROGRESS: f64 = 0.48;
pub const PANEL_EDGE_ACTIONS_REVEAL_SPAN: f64 = 0.52;
pub const PANEL_EDGE_ACTIONS_MIN_SCALE: f64 = 0.82;
pub const PANEL_PILL_BORDER_MAX_WIDTH: f64 = 1.0;
