//! 面板几何、动画、样式和运行时常量。

// --- geometry ---
pub const DEFAULT_PANEL_CANVAS_WIDTH: f64 = 420.0;
pub const COLLAPSED_PANEL_HEIGHT: f64 = 80.0;
pub const DEFAULT_COMPACT_PILL_WIDTH: f64 = 253.0;
pub const EXPANDED_PILL_WIDTH_DELTA: f64 = 30.0;
pub const DEFAULT_EXPANDED_PILL_WIDTH: f64 = DEFAULT_COMPACT_PILL_WIDTH + EXPANDED_PILL_WIDTH_DELTA;
pub const DEFAULT_COMPACT_PILL_HEIGHT: f64 = 37.0;
pub const COMPACT_SHOULDER_SIZE: f64 = 6.0;
pub const COMPACT_SHOULDER_CURVE_FACTOR: f64 = 0.62;
pub const COMPACT_PILL_RADIUS: f64 = 12.5;
pub const EXPANDED_PANEL_RADIUS: f64 = 12.0;
pub const CARD_RADIUS: f64 = 9.0;
pub const EXPANDED_MAX_BODY_HEIGHT: f64 = 420.0;
pub const EXPANDED_CARD_GAP: f64 = 8.0;
pub const EXPANDED_CONTENT_TOP_GAP: f64 = 9.0;
pub const EXPANDED_CONTENT_BOTTOM_INSET: f64 = 10.0;
pub const EXPANDED_CARDS_SIDE_INSET: f64 = 10.0;
pub const EXPANDED_CARD_OVERHANG: f64 = 0.0;
pub const EXPANDED_SEPARATOR_SIDE_INSET: f64 = 14.0;
pub const PANEL_DROP_DISTANCE: f64 = 4.5;
pub const PANEL_MORPH_PILL_RADIUS: f64 = 14.0;

// --- cards ---
pub const EMPTY_CARD_HEIGHT: f64 = 84.0;
pub const CARD_INSET_X: f64 = 10.0;
pub const CARD_HEADER_HEIGHT: f64 = 52.0;
pub const CARD_CHAT_PREFIX_WIDTH: f64 = 15.0;
pub const CARD_CHAT_LINE_HEIGHT: f64 = 16.0;
pub const CARD_CONTENT_BOTTOM_INSET: f64 = 8.0;
pub const CARD_CHAT_GAP: f64 = 4.0;
pub const CARD_TOOL_GAP: f64 = 7.0;
pub const CARD_PENDING_ACTION_Y: f64 = 9.0;
pub const CARD_PENDING_ACTION_HEIGHT: f64 = 18.0;
pub const CARD_PENDING_ACTION_GAP: f64 = 6.0;
pub const PENDING_PERMISSION_CARD_MIN_HEIGHT: f64 = 92.0;
pub const PENDING_PERMISSION_CARD_MAX_HEIGHT: f64 = 120.0;
pub const PENDING_QUESTION_CARD_MIN_HEIGHT: f64 = 108.0;
pub const PENDING_QUESTION_CARD_MAX_HEIGHT: f64 = 132.0;
pub const PENDING_QUESTION_CARD_OPTIONS_EXTRA_HEIGHT: f64 = 6.0;
pub const PENDING_QUESTION_CARD_FALLBACK_MAX_HEIGHT: f64 = 144.0;
pub const PROMPT_ASSIST_CARD_MIN_HEIGHT: f64 = 92.0;
pub const PROMPT_ASSIST_CARD_MAX_HEIGHT: f64 = 108.0;

// --- animation ---
pub const PANEL_MORPH_DELAY_MS: u64 = 120;
pub const PANEL_MORPH_MS: u64 = 270;
pub const PANEL_SHOULDER_HIDE_MS: u64 = 120;
pub const PANEL_HEIGHT_MS: u64 = 270;
pub const PANEL_OPEN_TOTAL_MS: u64 = 660;
pub const PANEL_CLOSE_TOTAL_MS: u64 = 660;
pub const PANEL_CLOSE_MORPH_DELAY_MS: u64 = 270;
pub const PANEL_CLOSE_SHOULDER_DELAY_MS: u64 = 540;
pub const PANEL_CLOSE_SHOULDER_MS: u64 = 120;
pub const PANEL_ANIMATION_FRAME_MS: u64 = 16;
pub const PANEL_CARD_REVEAL_MS: u64 = 320;
pub const PANEL_CARD_REVEAL_STAGGER_MS: u64 = 70;
pub const PANEL_CARD_EXIT_MS: u64 = 220;
pub const PANEL_CARD_EXIT_STAGGER_MS: u64 = 70;
pub const PANEL_CARD_EXIT_SETTLE_MS: u64 = 40;
pub const PANEL_SURFACE_SWITCH_HEIGHT_MS: u64 = 220;
pub const PANEL_SURFACE_SWITCH_CARD_REVEAL_MS: u64 = 220;
pub const PANEL_SURFACE_SWITCH_CARD_REVEAL_STAGGER_MS: u64 = 42;
pub const PANEL_SURFACE_SWITCH_INITIAL_CARD_PROGRESS: f64 = 0.24;
pub const PANEL_CARD_CONTENT_REVEAL_DELAY_PROGRESS: f64 = 0.18;
pub const PANEL_CARD_CONTENT_EARLY_EXIT_PROGRESS: f64 = 0.30;
pub const PANEL_CARD_REVEAL_Y: f64 = -8.0;

// --- active_count ---
pub const ACTIVE_COUNT_SLOT_WIDTH: f64 = 11.0;
pub const ACTIVE_COUNT_SLOT_NUDGE_X: f64 = 2.0;
pub const ACTIVE_COUNT_SCROLL_TRAVEL: f64 = 10.0;
pub const ACTIVE_COUNT_TEXT_WIDTH: f64 = 22.0;
pub const ACTIVE_COUNT_TEXT_OFFSET_X: f64 = ACTIVE_COUNT_SLOT_WIDTH - ACTIVE_COUNT_TEXT_WIDTH;
pub const ACTIVE_COUNT_LABEL_HEIGHT: f64 = 24.0;
pub const ACTIVE_COUNT_SCROLL_STEP_MS: u128 = 2300;
pub const ACTIVE_COUNT_SCROLL_HOLD_MS: u128 = 1000;
pub const ACTIVE_COUNT_SCROLL_MOVE_MS: u128 = 300;
pub const ACTIVE_COUNT_SCROLL_REFRESH_MS: u64 = 33;

// --- mascot ---
pub const MASCOT_ANIMATION_REFRESH_MS: u64 = 33;
pub const MASCOT_STATE_TRANSITION_SECONDS: f64 = 0.24;
pub const MASCOT_IDLE_LONG_SECONDS: u64 = 120;
pub const MASCOT_WAKE_ANGRY_SECONDS: f64 = 0.82;
pub const MASCOT_VERTICAL_NUDGE_Y: f64 = -2.0;

// --- runtime ---
pub const STATUS_QUEUE_REFRESH_MS: u64 = 33;
pub const HOVER_POLL_MS: u64 = 120;
pub const HOVER_DELAY_MS: u64 = 500;
pub const CARD_FOCUS_CLICK_DEBOUNCE_MS: u128 = 600;

// --- style ---
pub const PANEL_HIGHLIGHT_MAX_ALPHA: f64 = 0.12;
pub const PANEL_VISIBILITY_EPSILON: f64 = 0.02;
pub const PANEL_COMPACT_CORNER_MASK_MAX_PROGRESS: f64 = 0.01;
pub const PANEL_EDGE_ACTIONS_REVEAL_START_PROGRESS: f64 = 0.48;
pub const PANEL_EDGE_ACTIONS_REVEAL_SPAN: f64 = 0.52;
pub const PANEL_EDGE_ACTIONS_MIN_SCALE: f64 = 0.82;
pub const PANEL_PILL_BORDER_MAX_WIDTH: f64 = 1.0;
